trigger: none

pool: Default

steps:
- checkout: self

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      pwd

- script: git fetch
- script: git checkout $(branch)
- script: git pull
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      ls
